version: 2.1

# executors are environments in which a job runs. Here we use docker contaners.
executors:
  ruby-2-6:
    docker:
      - image: circleci/ruby:2.6.6-node-browsers
      - image: circleci/postgres:10.6
        environment:
          - POSTGRES_USER=draft_approve_test
          - POSTGRES_DB=draft_approve_test

  ruby-2-7:
    docker:
      - image: circleci/ruby:2.7.2-node-browsers
      - image: circleci/postgres:10.6
        environment:
          - POSTGRES_USER=draft_approve_test
          - POSTGRES_DB=draft_approve_test

  ruby-3-0:
    docker:
      - image: circleci/ruby:3.0.0-node-browsers
      - image: circleci/postgres:10.6
        environment:
          - POSTGRES_USER=draft_approve_test
          - POSTGRES_DB=draft_approve_test

# Each job is a separate run of a container. It can fail or succeed, depending on their steps.
# Jobs can be put together into workflows.
jobs:

  # We can use YAML to define a part of a job we alias as 'build', and then include it in other jobs to keep things DRY
  build-default: &build
    parameters:
      run-activerecord-5-2-x:
        type: boolean
        default: true
      run-activerecord-6-0-x:
        type: boolean
        default: true
      run-activerecord-6-1-x:
        type: boolean
        default: true

    # Specify a default executor for the job
    executor: ruby-2-6
    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install latest bundler
          command: |
            gem install bundler

      - run:
          name: install base dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle

      - run:
        # We use the Appraisal gem to automatically install & run tests against multiple versions of ActiveRecord
          name: install dependencies for each appraisal definition
          command: |
            bundle exec appraisal install

      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}

      - run:
          name: run tests
          command: |
            mkdir /tmp/test-results
            TEST_FILES="$(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)"
          when:
            condition: << parameters.run-activerecord-5-2-x >>
            steps:
              - run: bundle exec appraisal activerecord-5-2-x rspec
          when:
            condition: << parameters.run-activerecord-6-0-x >>
            steps:
              - run: bundle exec appraisal activerecord-6-0-x rspec
          when:
            condition: << parameters.run-activerecord-6-1-x >>
            steps:
              - run: bundle exec appraisal activerecord-6-1-x rspec

      # collect reports
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results

  # Specific build jobs for each ruby version
  build-ruby-2-6:
    <<: *build
    executor: ruby-2-6

  build-ruby-2-7:
    <<: *build
    executor: ruby-2-7

  build-ruby-3-0:
    <<: *build
    executor: ruby-3-0

# In the end we define a workflow, to run the build job for every ruby version
workflows:
  build_all_versions:
    jobs:
      - build-ruby-2-6
      - build-ruby-2-7
      - build-ruby-3-0:
        # Rails/ActiveRecord earlier than 6.x is not compatible with ruby 3
        run-activerecord-5-2-x: false
